# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# mosaic_rasters.py
# Created on: 2017-03-15 08:59:33.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import sys, string, os, arcgisscripting, arcpy

# Check out any necessary licenses
arcpy.CheckOutExtension("spatial")

# Create the Geoprocessor object
gp = arcgisscripting.create()

# Local variables:
s1dir = "D:\\OneDrive\\work\\GIS\\8_day_1km_LST\\LST_s12_2013\\lst_s1_2013\\"
s2dir = "D:\\OneDrive\\work\\GIS\\8_day_1km_LST\\LST_s12_2013\\lst_s2_2013\\"
outdir = "D:\\OneDrive\\work\\GIS\\8_day_1km_LST\\LST_s12_2013\\"
projdir = "D:\\OneDrive\\work\\research\\CHaMP\\GIS\\LST\\LST_s12_2013\\"
sr = r"D:\OneDrive\work\research\MODIS_sin.prj"
bands = 1
method = "First"
clMap = "First"


readFieldList = open("D:\\OneDrive\\work\\GIS\\8_day_1km_LST\\LST_s1_2001\\gridlist.txt", 'r')
FieldList = readFieldList.readlines()
readFieldList.close

for item in FieldList:
    item = item.replace("\n","")
    print item
    rast1 = s1dir + "lsts113" + item
    rast2 = s2dir + "lsts213" + item
    outrast = "lst_s1213" + item
    # Process: Mosaic To New Raster
    arcpy.MosaicToNewRaster_management([rast1, rast2], outdir, outrast, sr, "8_BIT_UNSIGNED", "926.6254331", bands, method, clMap)
    
