# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# projectRasters.py
# Created on: 2017-04-06 13:38:29.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy


# Local variables:
lst_s1213001 = "D:\\OneDrive\\work\\GIS\\8_day_1km_LST\\LST_s12_2013\\lst_s1213001"
test = "D:\\OneDrive\\work\\research\\CHaMP\\GIS\\LST\\LST_s12_2013\\test"

# Process: Project Raster
arcpy.ProjectRaster_management(lst_s1213001, test, "PROJCS['CRB_Albers_Equal_Area_Conic',GEOGCS['GCS_North_American_1983',DATUM['D_North_American_1983',SPHEROID['GRS_1980',6378137.0,298.257222101]],PRIMEM['Greenwich',0.0],UNIT['Degree',0.0174532925199433]],PROJECTION['Albers'],PARAMETER['False_Easting',700000.0],PARAMETER['False_Northing',0.0],PARAMETER['Central_Meridian',-117.0],PARAMETER['Standard_Parallel_1',43.0],PARAMETER['Standard_Parallel_2',48.0],PARAMETER['Latitude_Of_Origin',41.0],UNIT['Meter',1.0]]", "NEAREST", "926.6254331 926.6254331", "", "", "PROJCS['User_Defined_Sinusoidal',GEOGCS['GCS_User_Defined',DATUM['D_User_Defined',SPHEROID['User_Defined_Spheroid',6371007.181,0.0]],PRIMEM['Greenwich',0.0],UNIT['Degree',0.0174532925199433]],PROJECTION['Sinusoidal'],PARAMETER['False_Easting',0.0],PARAMETER['False_Northing',0.0],PARAMETER['central_meridian',0.0],UNIT['Meter',1.0]]")

