# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# mosaic_rasters.py
# Created on: 2017-03-15 08:59:33.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import sys, string, os, arcgisscripting, arcpy

# Check out any necessary licenses
arcpy.CheckOutExtension("spatial")

# Create the Geoprocessor object
gp = arcgisscripting.create()

# Local variables:
s1dir = "D:\\OneDrive\\work\\GIS\\8_day_1km_LST\\LST_s12_2011\\s1_2011\\"
s2dir = "D:\\OneDrive\\work\\GIS\\8_day_1km_LST\\LST_s12_2011\\s2_2011\\"
outdir = "D:\\OneDrive\\work\\GIS\\8_day_1km_LST\\LST_s12_2011\\"
projdir = "D:\\OneDrive\\work\\research\\CHaMP\\GIS\\LST\\LST_s12_2011\\"
sr = r"D:\OneDrive\work\research\MODIS_sin.prj"
bands = 1
method = "First"
clMap = "First"
sr2 = r"D:\OneDrive\work\research\CRB_Albers.prj"

readFieldList = open("D:\\OneDrive\\work\\GIS\\8_day_1km_LST\\LST_s1_2001\\gridlist.txt", 'r')
FieldList = readFieldList.readlines()
readFieldList.close

for item in FieldList:
    item = item.replace("\n","")
    print item
    outrast = outdir + "lst_s1211" + item
    projrast = projdir + outrast
    # Process: Mosaic To New Raster
    arcpy.ProjectRaster_management(outrast, projrast, sr2)
